#3 Modified the Team Member Data
anweshaiitp/Anwesha2k20-Android-App pull request #14
Opened 2019-12-09 19:05 UTC by Kavya-24

Changed the data and links for Team Members - Anwesha.

2019-12-10 04:07 UTC, atm1504 requested changes

2019-12-10 04:07 UTC, atm1504 commented on app/src/main/java/info/anwesha/iitp/team/TeamFragment.java
> +import static info.anwesha.iitp.R.drawable.rakshit_bhatt;
Remove this import. I hope its unnecessary

2019-12-10 04:07 UTC, atm1504 commented on app/src/main/java/info/anwesha/iitp/team/TeamFragment.java
> +        //allMembers.add(new info.anwesha.iitp.team.TeamItem("Piyush Tiwari", "Coordinator - Events and Operations", "9834943057", "https://www.facebook.com/thebackpropogator", R.drawable.piytwr_c1))
Remove the unwanted commented lines of code.

2019-12-13 20:45 UTC, s-ayush2903 approved these changes

2019-12-14 06:41 UTC, atm1504 commented on app/src/main/java/info/anwesha/iitp/team/TeamFragment.java
> +        allMembers.add(new info.anwesha.iitp.team.TeamItem("Rakshit Bhatt", "Coordinator - Hospitality", "9627765739", "https://m.facebook.com/",rakshit_bhat));
@Kavya-24 use R.drawable.rakshit_bhat here instead of rakshit_bhatt only. This will resolve the issue

2020-01-02 17:00 UTC, atm1504 approved these changes

2020-01-02 17:00 UTC, merged